version: '3'

services:
  hoshino:
    image: ghcr.io/witfog/hoshinobot
    restart: unless-stopped
    volumes:
      - config:/HoshinoBot/hoshino/config
      - modules:/HoshinoBot/hoshino/modules
      - img:/HoshinoBot/img
      - requirements:/HoshinoBot/requirements

volumes:
  config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/../volumes/config
  modules:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/../volumes/modules
  img:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/../volumes/img
  requirements:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/../volumes/requirements